application: blogachoo
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py

- url: /index\.html
  script: main.py

- url: /static/css
  static_dir: static/css

- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/images(.*\.(gif|png|jpg))

